export const DEFAULT_SERVICES = [
  { name: 'Website Development', description: 'Professional website development with modern design' },
  { name: 'Sales Funnel Setup', description: 'Complete sales funnel with conversion optimization' },
  { name: 'WhatsApp Automation', description: 'Automated WhatsApp messaging and responses' },
  { name: 'AI Chatbot Setup', description: 'Intelligent chatbot for customer support' },
  { name: 'Landing Pages', description: 'High-converting landing pages' },
  { name: 'SEO Setup', description: 'Search engine optimization for better rankings' },
  { name: 'Social Media Management', description: 'Complete social media management service' },
  { name: 'Instagram Growth System', description: 'Organic Instagram growth strategies' },
  { name: 'Lead Generation System', description: 'Automated lead generation and qualification' },
  { name: 'Branding Kit', description: 'Complete brand identity package' },
  { name: 'Logo Design', description: 'Professional logo design service' },
  { name: 'Video Editing', description: 'Professional video editing and production' },
  { name: 'AI Content Creation', description: 'AI-powered content generation' },
  { name: 'Email Marketing Setup', description: 'Email marketing automation setup' },
  { name: 'LinkedIn Outreach System', description: 'LinkedIn lead generation system' },
  { name: 'E-commerce Store Setup', description: 'Complete e-commerce store setup' },
  { name: 'No-Code App Development', description: 'Build apps without coding' },
  { name: 'Automation Setup', description: 'Business process automation' },
  { name: 'CRM Setup', description: 'Customer relationship management setup' },
  { name: 'AI Proposal Generator', description: 'Automated proposal generation' },
  { name: 'Pricing Strategy Consulting', description: 'Strategic pricing consultation' },
  { name: 'Funnel Optimization', description: 'Sales funnel optimization service' },
  { name: 'Copywriting Service', description: 'Professional copywriting' },
  { name: 'Reels Script Creation', description: 'Engaging reels scripts' },
  { name: 'AI Image Generation', description: 'AI-powered image creation' },
  { name: 'T-shirt POD Setup', description: 'Print-on-demand t-shirt business setup' },
  { name: 'Etsy Automation', description: 'Etsy store automation' },
  { name: 'Affiliate Marketing System', description: 'Complete affiliate marketing setup' },
  { name: 'Notion Dashboard Setup', description: 'Custom Notion workspace setup' },
  { name: 'Analytics Dashboard Setup', description: 'Business analytics dashboard' },
];
