/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OnboardingData = IDL.Record({
  'businessName' : IDL.Text,
  'goals' : IDL.Text,
  'niche' : IDL.Text,
  'budget' : IDL.Nat,
  'timeline' : IDL.Text,
});
export const CRMActivity = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'dueDate' : IDL.Opt(Time),
  'stage' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'leadId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
});
export const GeneratorLog = IDL.Record({
  'id' : IDL.Nat,
  'inputData' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'outputData' : IDL.Text,
  'generatorType' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'microNiche' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
  'channel' : IDL.Text,
});
export const LegalPage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastUpdatedAt' : Time,
  'lastUpdatedBy' : IDL.Principal,
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'offerType' : IDL.Text,
  'name' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'clientId' : IDL.Principal,
  'paymentStatus' : IDL.Text,
  'createdAt' : Time,
  'projectId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : IDL.Text,
  'clientId' : IDL.Principal,
  'onboardingData' : IDL.Opt(OnboardingData),
  'serviceId' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'pricePremium' : IDL.Nat,
  'priceBasic' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePro' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'businessName' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
});
export const Coupon = IDL.Record({
  'expiresAt' : IDL.Opt(Time),
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createCRMActivity' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(Time),
      ],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(Time)], [], []),
  'createGeneratorLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createLegalPage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOffer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createProject' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Opt(OnboardingData)],
      [IDL.Nat],
      [],
    ),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
  'getAllGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllLegalPages' : IDL.Func([], [IDL.Vec(LegalPage)], ['query']),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCRMActivitiesByLead' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CRMActivity)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'getLegalPage' : IDL.Func([IDL.Nat], [IDL.Opt(LegalPage)], ['query']),
  'getMyCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
  'getMyGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
  'getMyLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getOrdersByClient' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getOrdersByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectsByClient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleCoupon' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleOffer' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCRMActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateLegalPage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProjectStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OnboardingData = IDL.Record({
    'businessName' : IDL.Text,
    'goals' : IDL.Text,
    'niche' : IDL.Text,
    'budget' : IDL.Nat,
    'timeline' : IDL.Text,
  });
  const CRMActivity = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'dueDate' : IDL.Opt(Time),
    'stage' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'leadId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
  });
  const GeneratorLog = IDL.Record({
    'id' : IDL.Nat,
    'inputData' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'outputData' : IDL.Text,
    'generatorType' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'microNiche' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
    'channel' : IDL.Text,
  });
  const LegalPage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastUpdatedAt' : Time,
    'lastUpdatedBy' : IDL.Principal,
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'offerType' : IDL.Text,
    'name' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'clientId' : IDL.Principal,
    'paymentStatus' : IDL.Text,
    'createdAt' : Time,
    'projectId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : IDL.Text,
    'clientId' : IDL.Principal,
    'onboardingData' : IDL.Opt(OnboardingData),
    'serviceId' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'pricePremium' : IDL.Nat,
    'priceBasic' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePro' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'businessName' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
  });
  const Coupon = IDL.Record({
    'expiresAt' : IDL.Opt(Time),
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createCRMActivity' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(Time),
        ],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(Time)], [], []),
    'createGeneratorLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createLegalPage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOffer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createProject' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Opt(OnboardingData)],
        [IDL.Nat],
        [],
      ),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
    'getAllGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllLegalPages' : IDL.Func([], [IDL.Vec(LegalPage)], ['query']),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCRMActivitiesByLead' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CRMActivity)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'getLegalPage' : IDL.Func([IDL.Nat], [IDL.Opt(LegalPage)], ['query']),
    'getMyCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
    'getMyGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
    'getMyLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getOrdersByClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectsByClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleCoupon' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleOffer' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCRMActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateLegalPage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProjectStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };