import { useState } from 'react';
import { Receipt, Download, FileText, FileJson, FileSpreadsheet, Archive, Loader2, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useQuery } from '@tanstack/react-query';
import { useActor } from '../hooks/useActor';
import { useInternetIdentity } from '../hooks/useInternetIdentity';
import { Invoice } from '../backend';
import { toast } from 'sonner';

function useGetAllInvoices() {
  const { actor, isFetching } = useActor();
  const { identity } = useInternetIdentity();

  return useQuery<Invoice[]>({
    queryKey: ['allInvoices'],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getAllInvoices();
    },
    enabled: !!actor && !isFetching && !!identity,
  });
}

function useGetMyInvoices() {
  const { actor, isFetching } = useActor();
  const { identity } = useInternetIdentity();

  return useQuery<Invoice[]>({
    queryKey: ['myInvoices'],
    queryFn: async () => {
      if (!actor) return [];
      return actor.getMyInvoices();
    },
    enabled: !!actor && !isFetching && !!identity,
  });
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function getTimestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19) + 'Z';
}

function generateInvoicePDF(invoice: Invoice): string {
  return `INVOICE
${'='.repeat(60)}
Invoice ID: ${invoice.invoiceId}
Date: ${new Date(Number(invoice.createdAt) / 1_000_000).toLocaleDateString()}
Client ID: ${invoice.clientId.toString()}

SERVICE BREAKDOWN
${invoice.serviceBreakdown}

${'='.repeat(60)}
GST Amount:    $${(Number(invoice.gstAmount) / 100).toFixed(2)}
Total Paid:    $${(Number(invoice.totalPaid) / 100).toFixed(2)}
${'='.repeat(60)}

Generated by QuickBee AI Platform`;
}

export default function InvoiceHistoryPage() {
  const { data: allInvoices, isLoading: loadingAll } = useGetAllInvoices();
  const { data: myInvoices, isLoading: loadingMy } = useGetMyInvoices();
  const [search, setSearch] = useState('');

  // Use whichever returned data (admin gets all, user gets their own)
  const invoices = allInvoices ?? myInvoices ?? [];
  const isLoading = loadingAll || loadingMy;

  const filtered = invoices.filter(inv =>
    inv.invoiceId.toLowerCase().includes(search.toLowerCase()) ||
    inv.serviceBreakdown.toLowerCase().includes(search.toLowerCase())
  );

  const downloadInvoicePDF = (invoice: Invoice) => {
    const content = generateInvoicePDF(invoice);
    downloadFile(content, `invoice_${invoice.invoiceId}_${getTimestamp()}.txt`, 'text/plain');
    toast.success('Invoice downloaded');
  };

  const downloadAllCSV = () => {
    if (invoices.length === 0) { toast.error('No invoices to export'); return; }
    const rows = [['Invoice ID', 'Date', 'Client ID', 'Service Breakdown', 'GST Amount', 'Total Paid']];
    invoices.forEach(inv => rows.push([
      inv.invoiceId,
      new Date(Number(inv.createdAt) / 1_000_000).toLocaleDateString(),
      inv.clientId.toString(),
      `"${inv.serviceBreakdown.replace(/"/g, '""')}"`,
      (Number(inv.gstAmount) / 100).toFixed(2),
      (Number(inv.totalPaid) / 100).toFixed(2),
    ]));
    downloadFile(rows.map(r => r.join(',')).join('\n'), `invoices_history_${getTimestamp()}.csv`, 'text/csv');
    toast.success('CSV exported');
  };

  const downloadAllJSON = () => {
    if (invoices.length === 0) { toast.error('No invoices to export'); return; }
    const data = invoices.map(inv => ({
      invoiceId: inv.invoiceId,
      date: new Date(Number(inv.createdAt) / 1_000_000).toISOString(),
      clientId: inv.clientId.toString(),
      serviceBreakdown: inv.serviceBreakdown,
      gstAmount: Number(inv.gstAmount) / 100,
      totalPaid: Number(inv.totalPaid) / 100,
    }));
    downloadFile(JSON.stringify(data, null, 2), `invoices_archive_${getTimestamp()}.json`, 'application/json');
    toast.success('JSON archive exported');
  };

  const downloadBulkZIP = () => {
    // Generate a combined text file as ZIP alternative (JSZip not available)
    if (invoices.length === 0) { toast.error('No invoices to export'); return; }
    const combined = invoices.map(inv => generateInvoicePDF(inv)).join('\n\n' + '='.repeat(80) + '\n\n');
    downloadFile(combined, `invoices_bulk_${getTimestamp()}.txt`, 'text/plain');
    toast.success('Bulk invoice export downloaded');
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-2xl gradient-teal flex items-center justify-center neon-glow-sm">
            <Receipt className="w-6 h-6 text-[#0B0F14]" />
          </div>
          <div>
            <h1 className="text-2xl font-bold gradient-teal-text">Invoice History</h1>
            <p className="text-sm text-[oklch(0.60_0.02_200)]">{invoices.length} total invoices</p>
          </div>
        </div>

        {/* Export Actions */}
        <div className="flex flex-wrap items-center gap-2">
          <Button onClick={downloadAllCSV} variant="outline" size="sm"
            className="border-[oklch(0.82_0.18_175/0.3)] text-[oklch(0.82_0.18_175)] hover:bg-[oklch(0.82_0.18_175/0.1)] rounded-xl">
            <FileSpreadsheet className="w-3 h-3 mr-1" /> CSV
          </Button>
          <Button onClick={downloadAllJSON} variant="outline" size="sm"
            className="border-[oklch(0.82_0.18_175/0.3)] text-[oklch(0.82_0.18_175)] hover:bg-[oklch(0.82_0.18_175/0.1)] rounded-xl">
            <FileJson className="w-3 h-3 mr-1" /> JSON
          </Button>
          <Button onClick={downloadBulkZIP} variant="outline" size="sm"
            className="border-[oklch(0.82_0.18_175/0.3)] text-[oklch(0.82_0.18_175)] hover:bg-[oklch(0.82_0.18_175/0.1)] rounded-xl">
            <Archive className="w-3 h-3 mr-1" /> Bulk Export
          </Button>
        </div>
      </div>

      {/* Search */}
      <div className="relative max-w-sm">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[oklch(0.50_0.02_200)]" />
        <Input
          placeholder="Search invoices..."
          value={search}
          onChange={e => setSearch(e.target.value)}
          className="pl-10 bg-[oklch(0.14_0.015_200)] border-[oklch(0.20_0.02_200)] text-[oklch(0.90_0.01_200)] rounded-xl focus:border-[oklch(0.82_0.18_175/0.5)] placeholder-[oklch(0.45_0.02_200)]"
        />
      </div>

      {/* Table */}
      {isLoading ? (
        <div className="flex items-center justify-center py-16">
          <Loader2 className="w-8 h-8 animate-spin text-[oklch(0.82_0.18_175)]" />
        </div>
      ) : filtered.length === 0 ? (
        <div className="glass rounded-2xl p-12 border border-[oklch(0.82_0.18_175/0.1)] flex flex-col items-center justify-center gap-3 text-center">
          <div className="w-16 h-16 rounded-2xl bg-[oklch(0.82_0.18_175/0.1)] flex items-center justify-center">
            <Receipt className="w-8 h-8 text-[oklch(0.82_0.18_175/0.5)]" />
          </div>
          <p className="text-[oklch(0.60_0.02_200)]">No invoices found</p>
          <p className="text-sm text-[oklch(0.45_0.02_200)]">Invoices are generated automatically after successful payments</p>
        </div>
      ) : (
        <div className="glass rounded-2xl border border-[oklch(0.82_0.18_175/0.15)] overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-[oklch(0.82_0.18_175/0.1)] bg-[oklch(0.10_0.012_200)]">
                  <th className="text-left px-5 py-3 text-xs font-semibold text-[oklch(0.50_0.02_200)] uppercase tracking-wider">Invoice ID</th>
                  <th className="text-left px-5 py-3 text-xs font-semibold text-[oklch(0.50_0.02_200)] uppercase tracking-wider">Date</th>
                  <th className="text-left px-5 py-3 text-xs font-semibold text-[oklch(0.50_0.02_200)] uppercase tracking-wider">Service</th>
                  <th className="text-right px-5 py-3 text-xs font-semibold text-[oklch(0.50_0.02_200)] uppercase tracking-wider">GST</th>
                  <th className="text-right px-5 py-3 text-xs font-semibold text-[oklch(0.50_0.02_200)] uppercase tracking-wider">Total</th>
                  <th className="text-right px-5 py-3 text-xs font-semibold text-[oklch(0.50_0.02_200)] uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[oklch(0.82_0.18_175/0.05)]">
                {filtered.map(invoice => (
                  <tr key={invoice.invoiceId} className="hover:bg-[oklch(0.82_0.18_175/0.03)] transition-colors">
                    <td className="px-5 py-4">
                      <div className="flex items-center gap-2">
                        <div className="w-7 h-7 rounded-lg gradient-teal flex items-center justify-center shrink-0">
                          <FileText className="w-3 h-3 text-[#0B0F14]" />
                        </div>
                        <span className="text-sm font-mono text-[oklch(0.82_0.18_175)] truncate max-w-32">
                          {invoice.invoiceId}
                        </span>
                      </div>
                    </td>
                    <td className="px-5 py-4 text-sm text-[oklch(0.70_0.01_200)]">
                      {new Date(Number(invoice.createdAt) / 1_000_000).toLocaleDateString()}
                    </td>
                    <td className="px-5 py-4 text-sm text-[oklch(0.75_0.01_200)] max-w-48 truncate">
                      {invoice.serviceBreakdown}
                    </td>
                    <td className="px-5 py-4 text-sm text-right text-[oklch(0.70_0.01_200)]">
                      ${(Number(invoice.gstAmount) / 100).toFixed(2)}
                    </td>
                    <td className="px-5 py-4 text-right">
                      <span className="text-sm font-bold gradient-teal-text">
                        ${(Number(invoice.totalPaid) / 100).toFixed(2)}
                      </span>
                    </td>
                    <td className="px-5 py-4 text-right">
                      <Button
                        onClick={() => downloadInvoicePDF(invoice)}
                        variant="ghost"
                        size="sm"
                        className="text-[oklch(0.82_0.18_175)] hover:bg-[oklch(0.82_0.18_175/0.1)] rounded-xl"
                      >
                        <Download className="w-3 h-3 mr-1" /> PDF
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
