/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RecommendationOutput {
    projectedROI?: string;
    upsellSuggestion: string;
    budget?: bigint;
    recommendedService: string;
}
export interface PricingTier {
    features: Array<string>;
    price: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface IntegrationSettings {
    stripeEnabled: boolean;
    razorpayEnabled: boolean;
    automations: AutomationSettings;
    webhookUrl?: string;
}
export type ServicesResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Array<ManagedService>;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ManagedService {
    id: string;
    features: Array<string>;
    pricingType: PricingType;
    packages: Array<ServicePackage>;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    customRequirementLabel: string;
    deliveryTime: string;
    updatedAt: bigint;
    imageUrl: string;
    shortDescription: string;
    quantityEnabled: boolean;
    addOns: Array<ServiceAddOn>;
    isVisible: boolean;
    category: string;
    detailedDescription: string;
    basePrice: bigint;
    isUserCreated: boolean;
}
export type UpdateServiceResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: ManagedService;
};
export interface SalesSystemConfig {
    description: string;
    systemSettings: string;
    enabled: boolean;
    apiEndpoint: string;
    apiKey: string;
    systemName: string;
}
export interface ServiceAddOn {
    name: string;
    description: string;
    price: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Token {
    principal: Principal;
    issuedAt: Time;
    expiry: Time;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type ServiceCatalogResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: ManagedService;
};
export interface Service {
    id: bigint;
    qrCodeDataUrl?: string;
    features: Array<string>;
    pricingPro: PricingTier;
    subcategory: string;
    name: string;
    razorpayKeyId?: string;
    pricingBasic: PricingTier;
    description: string;
    settings: ServiceSettings;
    pricingPremium: PricingTier;
    razorpayOrderId?: string;
    razorpayEnabled: boolean;
    category: string;
    paymentLinkUrl?: string;
}
export type PasswordAuthResult = {
    __kind__: "ok";
    ok: Token;
} | {
    __kind__: "error";
    error: string;
};
export interface ServicePackage {
    features: Array<string>;
    name: string;
    deliveryTime: string;
    price: bigint;
}
export interface AutomationSettings {
    projectOnboarding: AutomationConfig;
    paymentConfirmation: AutomationConfig;
    sequenceBuilder: AutomationConfig;
    autoWhatsAppReplies: AutomationConfig;
    proposalAutoSend: AutomationConfig;
}
export interface AutomationConfig {
    enabled: boolean;
    config: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ServiceSettings {
    customMetadata: string;
    availability: string;
    isFeatured: boolean;
    isVisible: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    businessName?: string;
    email: string;
}
export enum PricingType {
    Hourly = "Hourly",
    Custom = "Custom",
    Fixed = "Fixed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createManagedService(service: ManagedService): Promise<ServiceCatalogResult>;
    createRecommendation(recommendation: RecommendationOutput): Promise<bigint>;
    deleteManagedService(id: string): Promise<ServiceCatalogResult>;
    deleteRecommendation(id: bigint): Promise<void>;
    duplicateManagedService(id: string): Promise<ServiceCatalogResult>;
    getAllRecommendations(): Promise<Array<RecommendationOutput>>;
    getAllServices(): Promise<Array<Service>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getIntegrationSettings(userId: Principal): Promise<IntegrationSettings | null>;
    getManagedService(id: string): Promise<ServiceCatalogResult>;
    getManagedServices(): Promise<Array<ManagedService>>;
    getManagedServicesByCategory(category: string): Promise<Array<ManagedService>>;
    getRecommendation(id: bigint): Promise<RecommendationOutput | null>;
    getSalesSystemConfig(userId: Principal): Promise<SalesSystemConfig | null>;
    getService(id: bigint): Promise<Service | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    login(email: string, password: string): Promise<PasswordAuthResult>;
    register(email: string, password: string, initialRole: UserRole): Promise<PasswordAuthResult>;
    reorderManagedServices(orderedIds: Array<string>): Promise<ServicesResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveIntegrationSettings(settings: IntegrationSettings): Promise<void>;
    saveSalesSystemConfig(config: SalesSystemConfig): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateManagedService(id: string, service: ManagedService): Promise<UpdateServiceResult>;
    updateRecommendation(id: bigint, recommendation: RecommendationOutput): Promise<void>;
}
import type { AutomationSettings as _AutomationSettings, IntegrationSettings as _IntegrationSettings, ManagedService as _ManagedService, PasswordAuthResult as _PasswordAuthResult, PricingTier as _PricingTier, PricingType as _PricingType, RecommendationOutput as _RecommendationOutput, SalesSystemConfig as _SalesSystemConfig, Service as _Service, ServiceAddOn as _ServiceAddOn, ServiceCatalogResult as _ServiceCatalogResult, ServicePackage as _ServicePackage, ServiceSettings as _ServiceSettings, ServicesResult as _ServicesResult, StripeSessionStatus as _StripeSessionStatus, Token as _Token, UpdateServiceResult as _UpdateServiceResult, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createManagedService(arg0: ManagedService): Promise<ServiceCatalogResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createManagedService(to_candid_ManagedService_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createManagedService(to_candid_ManagedService_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createRecommendation(arg0: RecommendationOutput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecommendation(to_candid_RecommendationOutput_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecommendation(to_candid_RecommendationOutput_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteManagedService(arg0: string): Promise<ServiceCatalogResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManagedService(arg0);
                return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManagedService(arg0);
            return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRecommendation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecommendation(arg0);
            return result;
        }
    }
    async duplicateManagedService(arg0: string): Promise<ServiceCatalogResult> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateManagedService(arg0);
                return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateManagedService(arg0);
            return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecommendations(): Promise<Array<RecommendationOutput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecommendations();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecommendations();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntegrationSettings(arg0: Principal): Promise<IntegrationSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntegrationSettings(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntegrationSettings(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManagedService(arg0: string): Promise<ServiceCatalogResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagedService(arg0);
                return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagedService(arg0);
            return from_candid_ServiceCatalogResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManagedServices(): Promise<Array<ManagedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagedServices();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagedServices();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManagedServicesByCategory(arg0: string): Promise<Array<ManagedService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManagedServicesByCategory(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManagedServicesByCategory(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendation(arg0: bigint): Promise<RecommendationOutput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendation(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendation(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesSystemConfig(arg0: Principal): Promise<SalesSystemConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesSystemConfig(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesSystemConfig(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<PasswordAuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_PasswordAuthResult_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_PasswordAuthResult_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string, arg2: UserRole): Promise<PasswordAuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PasswordAuthResult_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PasswordAuthResult_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderManagedServices(arg0: Array<string>): Promise<ServicesResult> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderManagedServices(arg0);
                return from_candid_ServicesResult_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderManagedServices(arg0);
            return from_candid_ServicesResult_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n48(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveIntegrationSettings(arg0: IntegrationSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIntegrationSettings(to_candid_IntegrationSettings_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIntegrationSettings(to_candid_IntegrationSettings_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveSalesSystemConfig(arg0: SalesSystemConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSalesSystemConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSalesSystemConfig(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateManagedService(arg0: string, arg1: ManagedService): Promise<UpdateServiceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateManagedService(arg0, to_candid_ManagedService_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UpdateServiceResult_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateManagedService(arg0, to_candid_ManagedService_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UpdateServiceResult_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecommendation(arg0: bigint, arg1: RecommendationOutput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecommendation(arg0, to_candid_RecommendationOutput_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecommendation(arg0, to_candid_RecommendationOutput_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_IntegrationSettings_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntegrationSettings): IntegrationSettings {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ManagedService_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagedService): ManagedService {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PasswordAuthResult_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PasswordAuthResult): PasswordAuthResult {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_PricingType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PricingType): PricingType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RecommendationOutput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecommendationOutput): RecommendationOutput {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCatalogResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCatalogResult): ServiceCatalogResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ServicesResult_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServicesResult): ServicesResult {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateServiceResult_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateServiceResult): UpdateServiceResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IntegrationSettings]): IntegrationSettings | null {
    return value.length === 0 ? null : from_candid_IntegrationSettings_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecommendationOutput]): RecommendationOutput | null {
    return value.length === 0 ? null : from_candid_RecommendationOutput_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesSystemConfig]): SalesSystemConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    features: Array<string>;
    pricingType: _PricingType;
    packages: Array<_ServicePackage>;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    customRequirementLabel: string;
    deliveryTime: string;
    updatedAt: bigint;
    imageUrl: string;
    shortDescription: string;
    quantityEnabled: boolean;
    addOns: Array<_ServiceAddOn>;
    isVisible: boolean;
    category: string;
    detailedDescription: string;
    basePrice: bigint;
    isUserCreated: boolean;
}): {
    id: string;
    features: Array<string>;
    pricingType: PricingType;
    packages: Array<ServicePackage>;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    customRequirementLabel: string;
    deliveryTime: string;
    updatedAt: bigint;
    imageUrl: string;
    shortDescription: string;
    quantityEnabled: boolean;
    addOns: Array<ServiceAddOn>;
    isVisible: boolean;
    category: string;
    detailedDescription: string;
    basePrice: bigint;
    isUserCreated: boolean;
} {
    return {
        id: value.id,
        features: value.features,
        pricingType: from_candid_PricingType_n18(_uploadFile, _downloadFile, value.pricingType),
        packages: value.packages,
        sortOrder: value.sortOrder,
        name: value.name,
        createdAt: value.createdAt,
        customRequirementLabel: value.customRequirementLabel,
        deliveryTime: value.deliveryTime,
        updatedAt: value.updatedAt,
        imageUrl: value.imageUrl,
        shortDescription: value.shortDescription,
        quantityEnabled: value.quantityEnabled,
        addOns: value.addOns,
        isVisible: value.isVisible,
        category: value.category,
        detailedDescription: value.detailedDescription,
        basePrice: value.basePrice,
        isUserCreated: value.isUserCreated
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectedROI: [] | [string];
    upsellSuggestion: string;
    budget: [] | [bigint];
    recommendedService: string;
}): {
    projectedROI?: string;
    upsellSuggestion: string;
    budget?: bigint;
    recommendedService: string;
} {
    return {
        projectedROI: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.projectedROI)),
        upsellSuggestion: value.upsellSuggestion,
        budget: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.budget)),
        recommendedService: value.recommendedService
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    qrCodeDataUrl: [] | [string];
    features: Array<string>;
    pricingPro: _PricingTier;
    subcategory: string;
    name: string;
    razorpayKeyId: [] | [string];
    pricingBasic: _PricingTier;
    description: string;
    settings: _ServiceSettings;
    pricingPremium: _PricingTier;
    razorpayOrderId: [] | [string];
    razorpayEnabled: boolean;
    category: string;
    paymentLinkUrl: [] | [string];
}): {
    id: bigint;
    qrCodeDataUrl?: string;
    features: Array<string>;
    pricingPro: PricingTier;
    subcategory: string;
    name: string;
    razorpayKeyId?: string;
    pricingBasic: PricingTier;
    description: string;
    settings: ServiceSettings;
    pricingPremium: PricingTier;
    razorpayOrderId?: string;
    razorpayEnabled: boolean;
    category: string;
    paymentLinkUrl?: string;
} {
    return {
        id: value.id,
        qrCodeDataUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.qrCodeDataUrl)),
        features: value.features,
        pricingPro: value.pricingPro,
        subcategory: value.subcategory,
        name: value.name,
        razorpayKeyId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.razorpayKeyId)),
        pricingBasic: value.pricingBasic,
        description: value.description,
        settings: value.settings,
        pricingPremium: value.pricingPremium,
        razorpayOrderId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.razorpayOrderId)),
        razorpayEnabled: value.razorpayEnabled,
        category: value.category,
        paymentLinkUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.paymentLinkUrl))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    businessName: [] | [string];
    email: string;
}): {
    name: string;
    businessName?: string;
    email: string;
} {
    return {
        name: value.name,
        businessName: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.businessName)),
        email: value.email
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeEnabled: boolean;
    razorpayEnabled: boolean;
    automations: _AutomationSettings;
    webhookUrl: [] | [string];
}): {
    stripeEnabled: boolean;
    razorpayEnabled: boolean;
    automations: AutomationSettings;
    webhookUrl?: string;
} {
    return {
        stripeEnabled: value.stripeEnabled,
        razorpayEnabled: value.razorpayEnabled,
        automations: value.automations,
        webhookUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.webhookUrl))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: _ManagedService;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: ManagedService;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_ManagedService_n16(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Hourly: null;
} | {
    Custom: null;
} | {
    Fixed: null;
}): PricingType {
    return "Hourly" in value ? PricingType.Hourly : "Custom" in value ? PricingType.Custom : "Fixed" in value ? PricingType.Fixed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n43(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Token;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: Token;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: Array<_ManagedService>;
}): {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Array<ManagedService>;
} {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: from_candid_vec_n37(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecommendationOutput>): Array<RecommendationOutput> {
    return value.map((x)=>from_candid_RecommendationOutput_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ManagedService>): Array<ManagedService> {
    return value.map((x)=>from_candid_ManagedService_n16(_uploadFile, _downloadFile, x));
}
function to_candid_IntegrationSettings_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntegrationSettings): _IntegrationSettings {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_ManagedService_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ManagedService): _ManagedService {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PricingType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PricingType): _PricingType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_RecommendationOutput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationOutput): _RecommendationOutput {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    features: Array<string>;
    pricingType: PricingType;
    packages: Array<ServicePackage>;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    customRequirementLabel: string;
    deliveryTime: string;
    updatedAt: bigint;
    imageUrl: string;
    shortDescription: string;
    quantityEnabled: boolean;
    addOns: Array<ServiceAddOn>;
    isVisible: boolean;
    category: string;
    detailedDescription: string;
    basePrice: bigint;
    isUserCreated: boolean;
}): {
    id: string;
    features: Array<string>;
    pricingType: _PricingType;
    packages: Array<_ServicePackage>;
    sortOrder: bigint;
    name: string;
    createdAt: bigint;
    customRequirementLabel: string;
    deliveryTime: string;
    updatedAt: bigint;
    imageUrl: string;
    shortDescription: string;
    quantityEnabled: boolean;
    addOns: Array<_ServiceAddOn>;
    isVisible: boolean;
    category: string;
    detailedDescription: string;
    basePrice: bigint;
    isUserCreated: boolean;
} {
    return {
        id: value.id,
        features: value.features,
        pricingType: to_candid_PricingType_n12(_uploadFile, _downloadFile, value.pricingType),
        packages: value.packages,
        sortOrder: value.sortOrder,
        name: value.name,
        createdAt: value.createdAt,
        customRequirementLabel: value.customRequirementLabel,
        deliveryTime: value.deliveryTime,
        updatedAt: value.updatedAt,
        imageUrl: value.imageUrl,
        shortDescription: value.shortDescription,
        quantityEnabled: value.quantityEnabled,
        addOns: value.addOns,
        isVisible: value.isVisible,
        category: value.category,
        detailedDescription: value.detailedDescription,
        basePrice: value.basePrice,
        isUserCreated: value.isUserCreated
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectedROI?: string;
    upsellSuggestion: string;
    budget?: bigint;
    recommendedService: string;
}): {
    projectedROI: [] | [string];
    upsellSuggestion: string;
    budget: [] | [bigint];
    recommendedService: string;
} {
    return {
        projectedROI: value.projectedROI ? candid_some(value.projectedROI) : candid_none(),
        upsellSuggestion: value.upsellSuggestion,
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        recommendedService: value.recommendedService
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    businessName?: string;
    email: string;
}): {
    name: string;
    businessName: [] | [string];
    email: string;
} {
    return {
        name: value.name,
        businessName: value.businessName ? candid_some(value.businessName) : candid_none(),
        email: value.email
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeEnabled: boolean;
    razorpayEnabled: boolean;
    automations: AutomationSettings;
    webhookUrl?: string;
}): {
    stripeEnabled: boolean;
    razorpayEnabled: boolean;
    automations: _AutomationSettings;
    webhookUrl: [] | [string];
} {
    return {
        stripeEnabled: value.stripeEnabled,
        razorpayEnabled: value.razorpayEnabled,
        automations: value.automations,
        webhookUrl: value.webhookUrl ? candid_some(value.webhookUrl) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PricingType): {
    Hourly: null;
} | {
    Custom: null;
} | {
    Fixed: null;
} {
    return value == PricingType.Hourly ? {
        Hourly: null
    } : value == PricingType.Custom ? {
        Custom: null
    } : value == PricingType.Fixed ? {
        Fixed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
