/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutomationConfig { 'enabled' : boolean, 'config' : string }
export interface AutomationSettings {
  'projectOnboarding' : AutomationConfig,
  'paymentConfirmation' : AutomationConfig,
  'sequenceBuilder' : AutomationConfig,
  'autoWhatsAppReplies' : AutomationConfig,
  'proposalAutoSend' : AutomationConfig,
}
export interface IntegrationSettings {
  'stripeEnabled' : boolean,
  'razorpayEnabled' : boolean,
  'automations' : AutomationSettings,
  'webhookUrl' : [] | [string],
}
export interface ManagedService {
  'id' : string,
  'features' : Array<string>,
  'pricingType' : PricingType,
  'packages' : Array<ServicePackage>,
  'sortOrder' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'customRequirementLabel' : string,
  'deliveryTime' : string,
  'updatedAt' : bigint,
  'imageUrl' : string,
  'shortDescription' : string,
  'quantityEnabled' : boolean,
  'addOns' : Array<ServiceAddOn>,
  'isVisible' : boolean,
  'category' : string,
  'detailedDescription' : string,
  'basePrice' : bigint,
  'isUserCreated' : boolean,
}
export type PasswordAuthResult = { 'ok' : Token } |
  { 'error' : string };
export interface PricingTier { 'features' : Array<string>, 'price' : bigint }
export type PricingType = { 'Hourly' : null } |
  { 'Custom' : null } |
  { 'Fixed' : null };
export interface RecommendationOutput {
  'projectedROI' : [] | [string],
  'upsellSuggestion' : string,
  'budget' : [] | [bigint],
  'recommendedService' : string,
}
export interface SalesSystemConfig {
  'description' : string,
  'systemSettings' : string,
  'enabled' : boolean,
  'apiEndpoint' : string,
  'apiKey' : string,
  'systemName' : string,
}
export interface Service {
  'id' : bigint,
  'qrCodeDataUrl' : [] | [string],
  'features' : Array<string>,
  'pricingPro' : PricingTier,
  'subcategory' : string,
  'name' : string,
  'razorpayKeyId' : [] | [string],
  'pricingBasic' : PricingTier,
  'description' : string,
  'settings' : ServiceSettings,
  'pricingPremium' : PricingTier,
  'razorpayOrderId' : [] | [string],
  'razorpayEnabled' : boolean,
  'category' : string,
  'paymentLinkUrl' : [] | [string],
}
export interface ServiceAddOn {
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type ServiceCatalogResult = { 'error' : string } |
  { 'success' : ManagedService };
export interface ServicePackage {
  'features' : Array<string>,
  'name' : string,
  'deliveryTime' : string,
  'price' : bigint,
}
export interface ServiceSettings {
  'customMetadata' : string,
  'availability' : string,
  'isFeatured' : boolean,
  'isVisible' : boolean,
}
export type ServicesResult = { 'error' : string } |
  { 'success' : Array<ManagedService> };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface Token {
  'principal' : Principal,
  'issuedAt' : Time,
  'expiry' : Time,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UpdateServiceResult = { 'error' : string } |
  { 'success' : ManagedService };
export interface UserProfile {
  'name' : string,
  'businessName' : [] | [string],
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createManagedService' : ActorMethod<[ManagedService], ServiceCatalogResult>,
  'createRecommendation' : ActorMethod<[RecommendationOutput], bigint>,
  'deleteManagedService' : ActorMethod<[string], ServiceCatalogResult>,
  'deleteRecommendation' : ActorMethod<[bigint], undefined>,
  'duplicateManagedService' : ActorMethod<[string], ServiceCatalogResult>,
  'getAllRecommendations' : ActorMethod<[], Array<RecommendationOutput>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getIntegrationSettings' : ActorMethod<
    [Principal],
    [] | [IntegrationSettings]
  >,
  'getManagedService' : ActorMethod<[string], ServiceCatalogResult>,
  'getManagedServices' : ActorMethod<[], Array<ManagedService>>,
  'getManagedServicesByCategory' : ActorMethod<[string], Array<ManagedService>>,
  'getRecommendation' : ActorMethod<[bigint], [] | [RecommendationOutput]>,
  'getSalesSystemConfig' : ActorMethod<[Principal], [] | [SalesSystemConfig]>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], PasswordAuthResult>,
  'register' : ActorMethod<[string, string, UserRole], PasswordAuthResult>,
  'reorderManagedServices' : ActorMethod<[Array<string>], ServicesResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveIntegrationSettings' : ActorMethod<[IntegrationSettings], undefined>,
  'saveSalesSystemConfig' : ActorMethod<[SalesSystemConfig], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateManagedService' : ActorMethod<
    [string, ManagedService],
    UpdateServiceResult
  >,
  'updateRecommendation' : ActorMethod<
    [bigint, RecommendationOutput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];