/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AutomationConfig { 'enabled' : boolean, 'config' : string }
export interface AutomationSettings {
  'projectOnboarding' : AutomationConfig,
  'paymentConfirmation' : AutomationConfig,
  'sequenceBuilder' : AutomationConfig,
  'autoWhatsAppReplies' : AutomationConfig,
  'proposalAutoSend' : AutomationConfig,
}
export interface CRMActivity {
  'id' : bigint,
  'activityType' : string,
  'assignedTo' : [] | [Principal],
  'createdAt' : Time,
  'createdBy' : Principal,
  'dueDate' : [] | [Time],
  'stage' : string,
  'projectId' : [] | [bigint],
  'leadId' : [] | [bigint],
  'notes' : string,
}
export interface Coupon {
  'expiresAt' : [] | [Time],
  'code' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
}
export interface GeneratorLog {
  'id' : bigint,
  'inputData' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'outputData' : string,
  'generatorType' : string,
}
export interface IntegrationSettings {
  'stripeEnabled' : boolean,
  'razorpayEnabled' : boolean,
  'automations' : AutomationSettings,
  'webhookUrl' : [] | [string],
}
export interface Lead {
  'id' : bigint,
  'status' : string,
  'urgencyLevel' : [] | [bigint],
  'assignedTo' : [] | [Principal],
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'email' : string,
  'microNiche' : string,
  'companySize' : [] | [string],
  'qualificationScore' : bigint,
  'phone' : [] | [string],
  'channel' : string,
  'budgetRange' : [] | [bigint],
  'decisionMakerStatus' : [] | [boolean],
}
export interface LegalPage {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'lastUpdatedAt' : Time,
  'lastUpdatedBy' : Principal,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'notificationType' : string,
  'createdAt' : Time,
  'isRead' : boolean,
  'message' : string,
}
export interface Offer {
  'id' : bigint,
  'offerType' : string,
  'name' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
}
export interface OnboardingData {
  'businessName' : string,
  'goals' : string,
  'niche' : string,
  'budget' : bigint,
  'timeline' : string,
}
export interface Order {
  'id' : bigint,
  'clientId' : Principal,
  'paymentStatus' : string,
  'createdAt' : Time,
  'projectId' : bigint,
  'amount' : bigint,
}
export interface PaymentLink {
  'id' : bigint,
  'qrCodeDataUrl' : [] | [string],
  'status' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'leadId' : bigint,
  'amount' : bigint,
  'paymentLinkUrl' : [] | [string],
}
export interface PricingTier { 'features' : Array<string>, 'price' : bigint }
export interface Project {
  'id' : bigint,
  'startTime' : Time,
  'status' : string,
  'clientId' : Principal,
  'onboardingData' : [] | [OnboardingData],
  'serviceId' : bigint,
}
export interface SalesSystemConfig {
  'description' : string,
  'systemSettings' : string,
  'enabled' : boolean,
  'apiEndpoint' : string,
  'apiKey' : string,
  'systemName' : string,
}
export interface Service {
  'id' : bigint,
  'qrCodeDataUrl' : [] | [string],
  'features' : Array<string>,
  'pricingPro' : PricingTier,
  'subcategory' : string,
  'name' : string,
  'razorpayKeyId' : [] | [string],
  'pricingBasic' : PricingTier,
  'description' : string,
  'settings' : ServiceSettings,
  'pricingPremium' : PricingTier,
  'razorpayOrderId' : [] | [string],
  'razorpayEnabled' : boolean,
  'category' : string,
  'paymentLinkUrl' : [] | [string],
}
export interface ServiceSettings {
  'customMetadata' : string,
  'availability' : string,
  'isFeatured' : boolean,
  'isVisible' : boolean,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'businessName' : [] | [string],
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLead' : ActorMethod<[bigint, Principal], undefined>,
  'createCRMActivity' : ActorMethod<
    [
      [] | [bigint],
      [] | [bigint],
      string,
      string,
      string,
      [] | [Principal],
      [] | [Time],
    ],
    bigint
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCoupon' : ActorMethod<[string, bigint, [] | [Time]], undefined>,
  'createGeneratorLog' : ActorMethod<[string, string, string], bigint>,
  'createLead' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      string,
      string,
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [boolean],
    ],
    bigint
  >,
  'createLegalPage' : ActorMethod<[string, string], bigint>,
  'createNotification' : ActorMethod<[Principal, string, string], bigint>,
  'createOffer' : ActorMethod<[string, bigint, string], bigint>,
  'createOrder' : ActorMethod<[bigint, bigint], bigint>,
  'createPaymentLink' : ActorMethod<[bigint, bigint], bigint>,
  'createProject' : ActorMethod<
    [Principal, bigint, [] | [OnboardingData]],
    bigint
  >,
  'createService' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      PricingTier,
      PricingTier,
      PricingTier,
      Array<string>,
      ServiceSettings,
      [] | [string],
      [] | [string],
      boolean,
      [] | [string],
      [] | [string],
    ],
    bigint
  >,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllCRMActivities' : ActorMethod<[], Array<CRMActivity>>,
  'getAllGeneratorLogs' : ActorMethod<[], Array<GeneratorLog>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllLegalPages' : ActorMethod<[], Array<LegalPage>>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getCRMActivitiesByLead' : ActorMethod<[bigint], Array<CRMActivity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'getIntegrationSettings' : ActorMethod<
    [Principal],
    [] | [IntegrationSettings]
  >,
  'getLeadsByScoreRange' : ActorMethod<[bigint, bigint], Array<Lead>>,
  'getLegalPage' : ActorMethod<[bigint], [] | [LegalPage]>,
  'getMyCRMActivities' : ActorMethod<[], Array<CRMActivity>>,
  'getMyGeneratorLogs' : ActorMethod<[], Array<GeneratorLog>>,
  'getMyLeads' : ActorMethod<[], Array<Lead>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyPaymentLinks' : ActorMethod<[], Array<PaymentLink>>,
  'getOrdersByClient' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByProject' : ActorMethod<[bigint], Array<Order>>,
  'getPaymentLinks' : ActorMethod<[], Array<PaymentLink>>,
  'getProject' : ActorMethod<[bigint], [] | [Project]>,
  'getProjectsByClient' : ActorMethod<[Principal], Array<Project>>,
  'getSalesSystemConfig' : ActorMethod<[Principal], [] | [SalesSystemConfig]>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getServiceRazorpayConfig' : ActorMethod<
    [bigint],
    [boolean, [] | [string], [] | [string]]
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRazorpayConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveIntegrationSettings' : ActorMethod<[IntegrationSettings], undefined>,
  'saveSalesSystemConfig' : ActorMethod<[SalesSystemConfig], undefined>,
  'setPaymentLinkQrCode' : ActorMethod<[bigint, string], undefined>,
  'setPaymentLinkUrl' : ActorMethod<[bigint, string], undefined>,
  'setRazorpayConfiguration' : ActorMethod<[string, string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleCoupon' : ActorMethod<[string, boolean], undefined>,
  'toggleOffer' : ActorMethod<[bigint, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCRMActivity' : ActorMethod<
    [bigint, string, string, string, [] | [Time]],
    undefined
  >,
  'updateLead' : ActorMethod<
    [
      bigint,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [boolean],
    ],
    undefined
  >,
  'updateLegalPage' : ActorMethod<[bigint, string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updatePaymentLinkStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProjectStatus' : ActorMethod<[bigint, string], undefined>,
  'updateService' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      PricingTier,
      PricingTier,
      PricingTier,
      Array<string>,
      ServiceSettings,
      [] | [string],
      [] | [string],
      boolean,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateServicePaymentInfo' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    undefined
  >,
  'updateServiceRazorpay' : ActorMethod<
    [bigint, boolean, [] | [string], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];