/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OnboardingData = IDL.Record({
  'businessName' : IDL.Text,
  'goals' : IDL.Text,
  'niche' : IDL.Text,
  'budget' : IDL.Nat,
  'timeline' : IDL.Text,
});
export const PricingTier = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const ServiceSettings = IDL.Record({
  'customMetadata' : IDL.Text,
  'availability' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'isVisible' : IDL.Bool,
});
export const CRMActivity = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'dueDate' : IDL.Opt(Time),
  'stage' : IDL.Text,
  'projectId' : IDL.Opt(IDL.Nat),
  'leadId' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
});
export const GeneratorLog = IDL.Record({
  'id' : IDL.Nat,
  'inputData' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'outputData' : IDL.Text,
  'generatorType' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'urgencyLevel' : IDL.Opt(IDL.Nat),
  'assignedTo' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'microNiche' : IDL.Text,
  'companySize' : IDL.Opt(IDL.Text),
  'qualificationScore' : IDL.Nat,
  'phone' : IDL.Opt(IDL.Text),
  'channel' : IDL.Text,
  'budgetRange' : IDL.Opt(IDL.Nat),
  'decisionMakerStatus' : IDL.Opt(IDL.Bool),
});
export const LegalPage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastUpdatedAt' : Time,
  'lastUpdatedBy' : IDL.Principal,
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'offerType' : IDL.Text,
  'name' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'clientId' : IDL.Principal,
  'paymentStatus' : IDL.Text,
  'createdAt' : Time,
  'projectId' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : IDL.Text,
  'clientId' : IDL.Principal,
  'onboardingData' : IDL.Opt(OnboardingData),
  'serviceId' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'qrCodeDataUrl' : IDL.Opt(IDL.Text),
  'features' : IDL.Vec(IDL.Text),
  'pricingPro' : PricingTier,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'razorpayKeyId' : IDL.Opt(IDL.Text),
  'pricingBasic' : PricingTier,
  'description' : IDL.Text,
  'settings' : ServiceSettings,
  'pricingPremium' : PricingTier,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'razorpayEnabled' : IDL.Bool,
  'category' : IDL.Text,
  'paymentLinkUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
});
export const Coupon = IDL.Record({
  'expiresAt' : IDL.Opt(Time),
  'code' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const AutomationConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'config' : IDL.Text,
});
export const AutomationSettings = IDL.Record({
  'projectOnboarding' : AutomationConfig,
  'paymentConfirmation' : AutomationConfig,
  'sequenceBuilder' : AutomationConfig,
  'autoWhatsAppReplies' : AutomationConfig,
  'proposalAutoSend' : AutomationConfig,
});
export const IntegrationSettings = IDL.Record({
  'stripeEnabled' : IDL.Bool,
  'razorpayEnabled' : IDL.Bool,
  'automations' : AutomationSettings,
  'webhookUrl' : IDL.Opt(IDL.Text),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const PaymentLink = IDL.Record({
  'id' : IDL.Nat,
  'qrCodeDataUrl' : IDL.Opt(IDL.Text),
  'status' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'leadId' : IDL.Nat,
  'amount' : IDL.Nat,
  'paymentLinkUrl' : IDL.Opt(IDL.Text),
});
export const SalesSystemConfig = IDL.Record({
  'description' : IDL.Text,
  'systemSettings' : IDL.Text,
  'enabled' : IDL.Bool,
  'apiEndpoint' : IDL.Text,
  'apiKey' : IDL.Text,
  'systemName' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'createCRMActivity' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Principal),
        IDL.Opt(Time),
      ],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(Time)], [], []),
  'createGeneratorLog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Nat],
      [],
    ),
  'createLegalPage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOffer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createPaymentLink' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'createProject' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Opt(OnboardingData)],
      [IDL.Nat],
      [],
    ),
  'createService' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PricingTier,
        PricingTier,
        PricingTier,
        IDL.Vec(IDL.Text),
        ServiceSettings,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
  'getAllGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllLegalPages' : IDL.Func([], [IDL.Vec(LegalPage)], ['query']),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCRMActivitiesByLead' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CRMActivity)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
  'getIntegrationSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IntegrationSettings)],
      ['query'],
    ),
  'getLeadsByScoreRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Lead)],
      ['query'],
    ),
  'getLegalPage' : IDL.Func([IDL.Nat], [IDL.Opt(LegalPage)], ['query']),
  'getMyCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
  'getMyGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
  'getMyLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyPaymentLinks' : IDL.Func([], [IDL.Vec(PaymentLink)], ['query']),
  'getOrdersByClient' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getOrdersByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getPaymentLinks' : IDL.Func([], [IDL.Vec(PaymentLink)], ['query']),
  'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
  'getProjectsByClient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getSalesSystemConfig' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SalesSystemConfig)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServiceRazorpayConfig' : IDL.Func(
      [IDL.Nat],
      [IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIntegrationSettings' : IDL.Func([IntegrationSettings], [], []),
  'saveSalesSystemConfig' : IDL.Func([SalesSystemConfig], [], []),
  'setPaymentLinkQrCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setPaymentLinkUrl' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setRazorpayConfiguration' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleCoupon' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleOffer' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCRMActivity' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [],
      [],
    ),
  'updateLegalPage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePaymentLinkStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateProjectStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateService' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        PricingTier,
        PricingTier,
        PricingTier,
        IDL.Vec(IDL.Text),
        ServiceSettings,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateServicePaymentInfo' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateServiceRazorpay' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OnboardingData = IDL.Record({
    'businessName' : IDL.Text,
    'goals' : IDL.Text,
    'niche' : IDL.Text,
    'budget' : IDL.Nat,
    'timeline' : IDL.Text,
  });
  const PricingTier = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const ServiceSettings = IDL.Record({
    'customMetadata' : IDL.Text,
    'availability' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'isVisible' : IDL.Bool,
  });
  const CRMActivity = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'dueDate' : IDL.Opt(Time),
    'stage' : IDL.Text,
    'projectId' : IDL.Opt(IDL.Nat),
    'leadId' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
  });
  const GeneratorLog = IDL.Record({
    'id' : IDL.Nat,
    'inputData' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'outputData' : IDL.Text,
    'generatorType' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'urgencyLevel' : IDL.Opt(IDL.Nat),
    'assignedTo' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'microNiche' : IDL.Text,
    'companySize' : IDL.Opt(IDL.Text),
    'qualificationScore' : IDL.Nat,
    'phone' : IDL.Opt(IDL.Text),
    'channel' : IDL.Text,
    'budgetRange' : IDL.Opt(IDL.Nat),
    'decisionMakerStatus' : IDL.Opt(IDL.Bool),
  });
  const LegalPage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastUpdatedAt' : Time,
    'lastUpdatedBy' : IDL.Principal,
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'offerType' : IDL.Text,
    'name' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'clientId' : IDL.Principal,
    'paymentStatus' : IDL.Text,
    'createdAt' : Time,
    'projectId' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : IDL.Text,
    'clientId' : IDL.Principal,
    'onboardingData' : IDL.Opt(OnboardingData),
    'serviceId' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'qrCodeDataUrl' : IDL.Opt(IDL.Text),
    'features' : IDL.Vec(IDL.Text),
    'pricingPro' : PricingTier,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'razorpayKeyId' : IDL.Opt(IDL.Text),
    'pricingBasic' : PricingTier,
    'description' : IDL.Text,
    'settings' : ServiceSettings,
    'pricingPremium' : PricingTier,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'razorpayEnabled' : IDL.Bool,
    'category' : IDL.Text,
    'paymentLinkUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
  });
  const Coupon = IDL.Record({
    'expiresAt' : IDL.Opt(Time),
    'code' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const AutomationConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'config' : IDL.Text,
  });
  const AutomationSettings = IDL.Record({
    'projectOnboarding' : AutomationConfig,
    'paymentConfirmation' : AutomationConfig,
    'sequenceBuilder' : AutomationConfig,
    'autoWhatsAppReplies' : AutomationConfig,
    'proposalAutoSend' : AutomationConfig,
  });
  const IntegrationSettings = IDL.Record({
    'stripeEnabled' : IDL.Bool,
    'razorpayEnabled' : IDL.Bool,
    'automations' : AutomationSettings,
    'webhookUrl' : IDL.Opt(IDL.Text),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const PaymentLink = IDL.Record({
    'id' : IDL.Nat,
    'qrCodeDataUrl' : IDL.Opt(IDL.Text),
    'status' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'leadId' : IDL.Nat,
    'amount' : IDL.Nat,
    'paymentLinkUrl' : IDL.Opt(IDL.Text),
  });
  const SalesSystemConfig = IDL.Record({
    'description' : IDL.Text,
    'systemSettings' : IDL.Text,
    'enabled' : IDL.Bool,
    'apiEndpoint' : IDL.Text,
    'apiKey' : IDL.Text,
    'systemName' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'createCRMActivity' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Opt(Time),
        ],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCoupon' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(Time)], [], []),
    'createGeneratorLog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Nat],
        [],
      ),
    'createLegalPage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOffer' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createPaymentLink' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'createProject' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Opt(OnboardingData)],
        [IDL.Nat],
        [],
      ),
    'createService' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PricingTier,
          PricingTier,
          PricingTier,
          IDL.Vec(IDL.Text),
          ServiceSettings,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
    'getAllGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllLegalPages' : IDL.Func([], [IDL.Vec(LegalPage)], ['query']),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCRMActivitiesByLead' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CRMActivity)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoupon' : IDL.Func([IDL.Text], [IDL.Opt(Coupon)], ['query']),
    'getIntegrationSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IntegrationSettings)],
        ['query'],
      ),
    'getLeadsByScoreRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Lead)],
        ['query'],
      ),
    'getLegalPage' : IDL.Func([IDL.Nat], [IDL.Opt(LegalPage)], ['query']),
    'getMyCRMActivities' : IDL.Func([], [IDL.Vec(CRMActivity)], ['query']),
    'getMyGeneratorLogs' : IDL.Func([], [IDL.Vec(GeneratorLog)], ['query']),
    'getMyLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyPaymentLinks' : IDL.Func([], [IDL.Vec(PaymentLink)], ['query']),
    'getOrdersByClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getOrdersByProject' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getPaymentLinks' : IDL.Func([], [IDL.Vec(PaymentLink)], ['query']),
    'getProject' : IDL.Func([IDL.Nat], [IDL.Opt(Project)], ['query']),
    'getProjectsByClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getSalesSystemConfig' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SalesSystemConfig)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServiceRazorpayConfig' : IDL.Func(
        [IDL.Nat],
        [IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIntegrationSettings' : IDL.Func([IntegrationSettings], [], []),
    'saveSalesSystemConfig' : IDL.Func([SalesSystemConfig], [], []),
    'setPaymentLinkQrCode' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setPaymentLinkUrl' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setRazorpayConfiguration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleCoupon' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleOffer' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCRMActivity' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [],
        [],
      ),
    'updateLegalPage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePaymentLinkStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateProjectStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PricingTier,
          PricingTier,
          PricingTier,
          IDL.Vec(IDL.Text),
          ServiceSettings,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateServicePaymentInfo' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateServiceRazorpay' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };