/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PricingType = IDL.Variant({
  'Hourly' : IDL.Null,
  'Custom' : IDL.Null,
  'Fixed' : IDL.Null,
});
export const ServicePackage = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'price' : IDL.Nat,
});
export const ServiceAddOn = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const ManagedService = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'pricingType' : PricingType,
  'packages' : IDL.Vec(ServicePackage),
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'customRequirementLabel' : IDL.Text,
  'deliveryTime' : IDL.Text,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'quantityEnabled' : IDL.Bool,
  'addOns' : IDL.Vec(ServiceAddOn),
  'isVisible' : IDL.Bool,
  'category' : IDL.Text,
  'detailedDescription' : IDL.Text,
  'basePrice' : IDL.Nat,
  'isUserCreated' : IDL.Bool,
});
export const ServiceCatalogResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : ManagedService,
});
export const RecommendationOutput = IDL.Record({
  'projectedROI' : IDL.Opt(IDL.Text),
  'upsellSuggestion' : IDL.Text,
  'budget' : IDL.Opt(IDL.Nat),
  'recommendedService' : IDL.Text,
});
export const PricingTier = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const ServiceSettings = IDL.Record({
  'customMetadata' : IDL.Text,
  'availability' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'isVisible' : IDL.Bool,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'qrCodeDataUrl' : IDL.Opt(IDL.Text),
  'features' : IDL.Vec(IDL.Text),
  'pricingPro' : PricingTier,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'razorpayKeyId' : IDL.Opt(IDL.Text),
  'pricingBasic' : PricingTier,
  'description' : IDL.Text,
  'settings' : ServiceSettings,
  'pricingPremium' : PricingTier,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'razorpayEnabled' : IDL.Bool,
  'category' : IDL.Text,
  'paymentLinkUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'businessName' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
});
export const AutomationConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'config' : IDL.Text,
});
export const AutomationSettings = IDL.Record({
  'projectOnboarding' : AutomationConfig,
  'paymentConfirmation' : AutomationConfig,
  'sequenceBuilder' : AutomationConfig,
  'autoWhatsAppReplies' : AutomationConfig,
  'proposalAutoSend' : AutomationConfig,
});
export const IntegrationSettings = IDL.Record({
  'stripeEnabled' : IDL.Bool,
  'razorpayEnabled' : IDL.Bool,
  'automations' : AutomationSettings,
  'webhookUrl' : IDL.Opt(IDL.Text),
});
export const SalesSystemConfig = IDL.Record({
  'description' : IDL.Text,
  'systemSettings' : IDL.Text,
  'enabled' : IDL.Bool,
  'apiEndpoint' : IDL.Text,
  'apiKey' : IDL.Text,
  'systemName' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Time = IDL.Int;
export const Token = IDL.Record({
  'principal' : IDL.Principal,
  'issuedAt' : Time,
  'expiry' : Time,
});
export const PasswordAuthResult = IDL.Variant({
  'ok' : Token,
  'error' : IDL.Text,
});
export const ServicesResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Vec(ManagedService),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateServiceResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : ManagedService,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createManagedService' : IDL.Func(
      [ManagedService],
      [ServiceCatalogResult],
      [],
    ),
  'createRecommendation' : IDL.Func([RecommendationOutput], [IDL.Nat], []),
  'deleteManagedService' : IDL.Func([IDL.Text], [ServiceCatalogResult], []),
  'deleteRecommendation' : IDL.Func([IDL.Nat], [], []),
  'duplicateManagedService' : IDL.Func([IDL.Text], [ServiceCatalogResult], []),
  'getAllRecommendations' : IDL.Func(
      [],
      [IDL.Vec(RecommendationOutput)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIntegrationSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IntegrationSettings)],
      ['query'],
    ),
  'getManagedService' : IDL.Func([IDL.Text], [ServiceCatalogResult], ['query']),
  'getManagedServices' : IDL.Func([], [IDL.Vec(ManagedService)], ['query']),
  'getManagedServicesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ManagedService)],
      ['query'],
    ),
  'getRecommendation' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RecommendationOutput)],
      ['query'],
    ),
  'getSalesSystemConfig' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SalesSystemConfig)],
      ['query'],
    ),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [PasswordAuthResult], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole],
      [PasswordAuthResult],
      [],
    ),
  'reorderManagedServices' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [ServicesResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIntegrationSettings' : IDL.Func([IntegrationSettings], [], []),
  'saveSalesSystemConfig' : IDL.Func([SalesSystemConfig], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateManagedService' : IDL.Func(
      [IDL.Text, ManagedService],
      [UpdateServiceResult],
      [],
    ),
  'updateRecommendation' : IDL.Func([IDL.Nat, RecommendationOutput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PricingType = IDL.Variant({
    'Hourly' : IDL.Null,
    'Custom' : IDL.Null,
    'Fixed' : IDL.Null,
  });
  const ServicePackage = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ServiceAddOn = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ManagedService = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'pricingType' : PricingType,
    'packages' : IDL.Vec(ServicePackage),
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'customRequirementLabel' : IDL.Text,
    'deliveryTime' : IDL.Text,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'quantityEnabled' : IDL.Bool,
    'addOns' : IDL.Vec(ServiceAddOn),
    'isVisible' : IDL.Bool,
    'category' : IDL.Text,
    'detailedDescription' : IDL.Text,
    'basePrice' : IDL.Nat,
    'isUserCreated' : IDL.Bool,
  });
  const ServiceCatalogResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : ManagedService,
  });
  const RecommendationOutput = IDL.Record({
    'projectedROI' : IDL.Opt(IDL.Text),
    'upsellSuggestion' : IDL.Text,
    'budget' : IDL.Opt(IDL.Nat),
    'recommendedService' : IDL.Text,
  });
  const PricingTier = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const ServiceSettings = IDL.Record({
    'customMetadata' : IDL.Text,
    'availability' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'isVisible' : IDL.Bool,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'qrCodeDataUrl' : IDL.Opt(IDL.Text),
    'features' : IDL.Vec(IDL.Text),
    'pricingPro' : PricingTier,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'razorpayKeyId' : IDL.Opt(IDL.Text),
    'pricingBasic' : PricingTier,
    'description' : IDL.Text,
    'settings' : ServiceSettings,
    'pricingPremium' : PricingTier,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'razorpayEnabled' : IDL.Bool,
    'category' : IDL.Text,
    'paymentLinkUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'businessName' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
  });
  const AutomationConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'config' : IDL.Text,
  });
  const AutomationSettings = IDL.Record({
    'projectOnboarding' : AutomationConfig,
    'paymentConfirmation' : AutomationConfig,
    'sequenceBuilder' : AutomationConfig,
    'autoWhatsAppReplies' : AutomationConfig,
    'proposalAutoSend' : AutomationConfig,
  });
  const IntegrationSettings = IDL.Record({
    'stripeEnabled' : IDL.Bool,
    'razorpayEnabled' : IDL.Bool,
    'automations' : AutomationSettings,
    'webhookUrl' : IDL.Opt(IDL.Text),
  });
  const SalesSystemConfig = IDL.Record({
    'description' : IDL.Text,
    'systemSettings' : IDL.Text,
    'enabled' : IDL.Bool,
    'apiEndpoint' : IDL.Text,
    'apiKey' : IDL.Text,
    'systemName' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Time = IDL.Int;
  const Token = IDL.Record({
    'principal' : IDL.Principal,
    'issuedAt' : Time,
    'expiry' : Time,
  });
  const PasswordAuthResult = IDL.Variant({ 'ok' : Token, 'error' : IDL.Text });
  const ServicesResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Vec(ManagedService),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateServiceResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : ManagedService,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createManagedService' : IDL.Func(
        [ManagedService],
        [ServiceCatalogResult],
        [],
      ),
    'createRecommendation' : IDL.Func([RecommendationOutput], [IDL.Nat], []),
    'deleteManagedService' : IDL.Func([IDL.Text], [ServiceCatalogResult], []),
    'deleteRecommendation' : IDL.Func([IDL.Nat], [], []),
    'duplicateManagedService' : IDL.Func(
        [IDL.Text],
        [ServiceCatalogResult],
        [],
      ),
    'getAllRecommendations' : IDL.Func(
        [],
        [IDL.Vec(RecommendationOutput)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIntegrationSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IntegrationSettings)],
        ['query'],
      ),
    'getManagedService' : IDL.Func(
        [IDL.Text],
        [ServiceCatalogResult],
        ['query'],
      ),
    'getManagedServices' : IDL.Func([], [IDL.Vec(ManagedService)], ['query']),
    'getManagedServicesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ManagedService)],
        ['query'],
      ),
    'getRecommendation' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RecommendationOutput)],
        ['query'],
      ),
    'getSalesSystemConfig' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SalesSystemConfig)],
        ['query'],
      ),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [PasswordAuthResult], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole],
        [PasswordAuthResult],
        [],
      ),
    'reorderManagedServices' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [ServicesResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIntegrationSettings' : IDL.Func([IntegrationSettings], [], []),
    'saveSalesSystemConfig' : IDL.Func([SalesSystemConfig], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateManagedService' : IDL.Func(
        [IDL.Text, ManagedService],
        [UpdateServiceResult],
        [],
      ),
    'updateRecommendation' : IDL.Func([IDL.Nat, RecommendationOutput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };