/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OnboardingData {
    businessName: string;
    goals: string;
    niche: string;
    budget: bigint;
    timeline: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Coupon {
    expiresAt?: Time;
    code: string;
    discountPercent: bigint;
    isActive: boolean;
}
export interface Service {
    id: bigint;
    pricePremium: bigint;
    priceBasic: bigint;
    name: string;
    description: string;
    pricePro: bigint;
}
export interface Order {
    id: bigint;
    clientId: Principal;
    paymentStatus: string;
    createdAt: Time;
    projectId: bigint;
    amount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LegalPage {
    id: bigint;
    title: string;
    content: string;
    lastUpdatedAt: Time;
    lastUpdatedBy: Principal;
}
export interface Lead {
    id: bigint;
    status: string;
    assignedTo?: Principal;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    email: string;
    microNiche: string;
    phone?: string;
    channel: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CRMActivity {
    id: bigint;
    activityType: string;
    assignedTo?: Principal;
    createdAt: Time;
    createdBy: Principal;
    dueDate?: Time;
    stage: string;
    projectId?: bigint;
    leadId?: bigint;
    notes: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Offer {
    id: bigint;
    offerType: string;
    name: string;
    discountPercent: bigint;
    isActive: boolean;
}
export interface Notification {
    id: bigint;
    userId: Principal;
    notificationType: string;
    createdAt: Time;
    isRead: boolean;
    message: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Project {
    id: bigint;
    startTime: Time;
    status: string;
    clientId: Principal;
    onboardingData?: OnboardingData;
    serviceId: bigint;
}
export interface GeneratorLog {
    id: bigint;
    inputData: string;
    userId: Principal;
    createdAt: Time;
    outputData: string;
    generatorType: string;
}
export interface UserProfile {
    name: string;
    role: string;
    businessName?: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addService(name: string, description: string, priceBasic: bigint, pricePro: bigint, pricePremium: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignLead(leadId: bigint, userId: Principal): Promise<void>;
    createCRMActivity(leadId: bigint | null, projectId: bigint | null, activityType: string, stage: string, notes: string, assignedTo: Principal | null, dueDate: Time | null): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCoupon(code: string, discountPercent: bigint, expiresAt: Time | null): Promise<void>;
    createGeneratorLog(generatorType: string, inputData: string, outputData: string): Promise<bigint>;
    createLead(name: string, email: string, phone: string | null, channel: string, microNiche: string): Promise<bigint>;
    createLegalPage(title: string, content: string): Promise<bigint>;
    createNotification(userId: Principal, message: string, notificationType: string): Promise<bigint>;
    createOffer(name: string, discountPercent: bigint, offerType: string): Promise<bigint>;
    createOrder(projectId: bigint, amount: bigint): Promise<bigint>;
    createProject(clientId: Principal, serviceId: bigint, onboardingData: OnboardingData | null): Promise<bigint>;
    deleteLead(id: bigint): Promise<void>;
    deleteService(id: bigint): Promise<void>;
    getAllCRMActivities(): Promise<Array<CRMActivity>>;
    getAllGeneratorLogs(): Promise<Array<GeneratorLog>>;
    getAllLeads(): Promise<Array<Lead>>;
    getAllLegalPages(): Promise<Array<LegalPage>>;
    getAllOffers(): Promise<Array<Offer>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllServices(): Promise<Array<Service>>;
    getCRMActivitiesByLead(leadId: bigint): Promise<Array<CRMActivity>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoupon(code: string): Promise<Coupon | null>;
    getLegalPage(id: bigint): Promise<LegalPage | null>;
    getMyCRMActivities(): Promise<Array<CRMActivity>>;
    getMyGeneratorLogs(): Promise<Array<GeneratorLog>>;
    getMyLeads(): Promise<Array<Lead>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getOrdersByClient(clientId: Principal): Promise<Array<Order>>;
    getOrdersByProject(projectId: bigint): Promise<Array<Order>>;
    getProject(id: bigint): Promise<Project | null>;
    getProjectsByClient(clientId: Principal): Promise<Array<Project>>;
    getService(id: bigint): Promise<Service | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    markNotificationAsRead(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleCoupon(code: string, isActive: boolean): Promise<void>;
    toggleOffer(id: bigint, isActive: boolean): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCRMActivity(id: bigint, activityType: string, stage: string, notes: string, dueDate: Time | null): Promise<void>;
    updateLead(id: bigint, name: string, email: string, phone: string | null, channel: string, microNiche: string, status: string): Promise<void>;
    updateLegalPage(id: bigint, title: string, content: string): Promise<void>;
    updateOrderStatus(id: bigint, status: string): Promise<void>;
    updateProjectStatus(id: bigint, status: string): Promise<void>;
    updateService(id: bigint, name: string, description: string, priceBasic: bigint, pricePro: bigint, pricePremium: bigint): Promise<void>;
}
import type { CRMActivity as _CRMActivity, Coupon as _Coupon, Lead as _Lead, LegalPage as _LegalPage, OnboardingData as _OnboardingData, Project as _Project, Service as _Service, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addService(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignLead(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLead(arg0, arg1);
            return result;
        }
    }
    async createCRMActivity(arg0: bigint | null, arg1: bigint | null, arg2: string, arg3: string, arg4: string, arg5: Principal | null, arg6: Time | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCRMActivity(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCRMActivity(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCoupon(arg0: string, arg1: bigint, arg2: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createGeneratorLog(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createGeneratorLog(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGeneratorLog(arg0, arg1, arg2);
            return result;
        }
    }
    async createLead(arg0: string, arg1: string, arg2: string | null, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async createLegalPage(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLegalPage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLegalPage(arg0, arg1);
            return result;
        }
    }
    async createNotification(arg0: Principal, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async createOffer(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOffer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOffer(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1);
            return result;
        }
    }
    async createProject(arg0: Principal, arg1: bigint, arg2: OnboardingData | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAllCRMActivities(): Promise<Array<CRMActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCRMActivities();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCRMActivities();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGeneratorLogs(): Promise<Array<GeneratorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGeneratorLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGeneratorLogs();
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLegalPages(): Promise<Array<LegalPage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLegalPages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLegalPages();
            return result;
        }
    }
    async getAllOffers(): Promise<Array<Offer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOffers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOffers();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return result;
        }
    }
    async getCRMActivitiesByLead(arg0: bigint): Promise<Array<CRMActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCRMActivitiesByLead(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCRMActivitiesByLead(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoupon(arg0: string): Promise<Coupon | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoupon(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoupon(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegalPage(arg0: bigint): Promise<LegalPage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalPage(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalPage(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCRMActivities(): Promise<Array<CRMActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCRMActivities();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCRMActivities();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGeneratorLogs(): Promise<Array<GeneratorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGeneratorLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGeneratorLogs();
            return result;
        }
    }
    async getMyLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeads();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeads();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getOrdersByClient(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByClient(arg0);
            return result;
        }
    }
    async getOrdersByProject(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByProject(arg0);
            return result;
        }
    }
    async getProject(arg0: bigint): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectsByClient(arg0: Principal): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByClient(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByClient(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: bigint): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleCoupon(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCoupon(arg0, arg1);
            return result;
        }
    }
    async toggleOffer(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleOffer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleOffer(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCRMActivity(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCRMActivity(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCRMActivity(arg0, arg1, arg2, arg3, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async updateLegalPage(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLegalPage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLegalPage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1);
            return result;
        }
    }
    async updateProjectStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectStatus(arg0, arg1);
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_CRMActivity_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CRMActivity): CRMActivity {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OnboardingData]): OnboardingData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coupon]): Coupon | null {
    return value.length === 0 ? null : from_candid_Coupon_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LegalPage]): LegalPage | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityType: string;
    assignedTo: [] | [Principal];
    createdAt: _Time;
    createdBy: Principal;
    dueDate: [] | [_Time];
    stage: string;
    projectId: [] | [bigint];
    leadId: [] | [bigint];
    notes: string;
}): {
    id: bigint;
    activityType: string;
    assignedTo?: Principal;
    createdAt: Time;
    createdBy: Principal;
    dueDate?: Time;
    stage: string;
    projectId?: bigint;
    leadId?: bigint;
    notes: string;
} {
    return {
        id: value.id,
        activityType: value.activityType,
        assignedTo: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.assignedTo)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        dueDate: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.dueDate)),
        stage: value.stage,
        projectId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.projectId)),
        leadId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.leadId)),
        notes: value.notes
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    assignedTo: [] | [Principal];
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    email: string;
    microNiche: string;
    phone: [] | [string];
    channel: string;
}): {
    id: bigint;
    status: string;
    assignedTo?: Principal;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    email: string;
    microNiche: string;
    phone?: string;
    channel: string;
} {
    return {
        id: value.id,
        status: value.status,
        assignedTo: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.assignedTo)),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        microNiche: value.microNiche,
        phone: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.phone)),
        channel: value.channel
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    status: string;
    clientId: Principal;
    onboardingData: [] | [_OnboardingData];
    serviceId: bigint;
}): {
    id: bigint;
    startTime: Time;
    status: string;
    clientId: Principal;
    onboardingData?: OnboardingData;
    serviceId: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: value.status,
        clientId: value.clientId,
        onboardingData: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.onboardingData)),
        serviceId: value.serviceId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    businessName: [] | [string];
    email: string;
}): {
    name: string;
    role: string;
    businessName?: string;
    email: string;
} {
    return {
        name: value.name,
        role: value.role,
        businessName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.businessName)),
        email: value.email
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [_Time];
    code: string;
    discountPercent: bigint;
    isActive: boolean;
}): {
    expiresAt?: Time;
    code: string;
    discountPercent: bigint;
    isActive: boolean;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.expiresAt)),
        code: value.code,
        discountPercent: value.discountPercent,
        isActive: value.isActive
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n35(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CRMActivity>): Array<CRMActivity> {
    return value.map((x)=>from_candid_CRMActivity_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OnboardingData | null): [] | [_OnboardingData] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    businessName?: string;
    email: string;
}): {
    name: string;
    role: string;
    businessName: [] | [string];
    email: string;
} {
    return {
        name: value.name,
        role: value.role,
        businessName: value.businessName ? candid_some(value.businessName) : candid_none(),
        email: value.email
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
